platform:
  sys:
    version: '@project.version@'

# 启用热部署
spring:
  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**,templates/**
      poll-interval: 5000
      quiet-period: 2000
    livereload:
      enabled: true